### PR TITLE
Add scaling_configuration

### PR DESCRIPTION
**Pull request by rfvermut**
PR for #41

### CODE REVIEW

**Comment by rigobcastro** [comment]
Must to have!

**Comment by pierresteiner** [comment]
We could use that as well

**Comment by antonbabenko** [comment]
Thanks for this addition, @rfvermut !

[v1.19.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v1.19.0) has been just released.

**Comment by antonbabenko** [comment]
For Terraform 0.12 users - [v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.4.0) has been released with this feature available.

Check [examples/serverless](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/841228bf15985311aa77eb2683e5b680b7285b8a/examples/serverless/main.tf#L19-L46) for serverless usage:

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/841228bf15985311aa77eb2683e5b680b7285b8a/examples/serverless/main.tf#L19-L46

**Pull request merged**
