### PR TITLE
feat: add "this_rds_cluster_instance_ids" to module outputs

### PR DESCRIPTION
**Pull request by tomasbackman**
# Description

In issue #82 this was requested, so added output of it in module and all current examples.

### CODE REVIEW

**Comment by tomasbackman** [comment]
Tried to link the PR to the issue by following: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue but was unsuccessful..

**Comment by bryantbiggs** [comment]
hi @tomasbackman - thank you for the PR! could you rebase/merge with master to update your branch and change your PR title to something like `feat: add "this_rds_cluster_instance_ids" to module outputs` please?

**Comment by tomasbackman** [comment]
> hi @tomasbackman - thank you for the PR! could you rebase/merge with master to update your branch and change your PR title to something like `feat: add "this_rds_cluster_instance_ids" to module outputs` please?

Fixed! =)

**Comment by bryantbiggs** [comment]
Thank you! @antonbabenko 🤘🏼

**Comment by antonbabenko** [comment]
Done. [v2.19.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.19.0) has been just released.

**Pull request merged**
