### PR TITLE
feat: Add `security_group_use_name_prefix` variable to enable/disable name prefix usage

### PR DESCRIPTION
**Pull request by naseemkullah**
## Description

Add `security_group_use_name_prefix` that defaults to true, which toggles wether to use name_prefix or name within the security group

## Motivation and Context

name/name-prefix changes in security groups are destructive, in order to import resources to this module I need to be able to use just name and not name_prefix. 

## Breaking Changes

keeping name-prefix as the default does not introduce breaking changes

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
Thanks for the PR @naseemkullah ! can you please run `pre-commit run -a` to update the docs please

**Comment by naseemkullah** [comment]
@bryantbiggs np! doing so now, would it be possible to cut a release immediately upon merging? I am in the middle of migrating state from a diff module to this one

**Comment by bryantbiggs** [comment]
@naseemkullah releases are automatic after each merge

**Comment by naseemkullah** [comment]
> @naseemkullah releases are automatic after each merge

Great! Checks passing.

**Comment by naseemkullah** [comment]
> @naseemkullah releases are automatic after each merge

Alright, perfect! Looking forward to it.

**Review by bryantbiggs — APPROVED** [review]
looks good to me - @antonbabenko  your thoughts?

**Review by antonbabenko — APPROVED** [review]
As long as it is backward-compatible, it is good.

**Comment by antonbabenko** [comment]
This PR is included in version 7.1.0 :tada:

**Pull request merged**
