### PR TITLE
fix: update CI/CD process to enable auto-release workflow

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- add new hook to pre-commit to fix eof lines
- add new `release.yml` workflow. this workflow will automatically:
	- create and push new tag for next [semver based on conventional-commits](https://github.com/semantic-release/semantic-release#commit-message-format)
	- create GitHub release with notes
	- update Changelog with release notes
	- this workflow will also automatically notify PRs that are included in the release, mimicking the manual behavior but now its automated https://github.com/clowdhaus/terraform-aws-rds/pull/1#issuecomment-952097291
- remove old `chglog` configs and Makefile

## Motivation and Context
- automate release process in a standardized manner
- standardize new CI workflow (copying from RDS)

## Breaking Changes
- No

## How Has This Been Tested?
- [x] https://github.com/terraform-aws-modules/terraform-aws-rds/pull/361

### CODE REVIEW

**Comment by antonbabenko** [comment]
Any ideas why this merge has not triggered the release?

**Comment by bryantbiggs** [comment]
there were no file patterns matched that would trigger the release workflow - https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/.github/workflows/release.yml#L8-L10

**Comment by antonbabenko** [comment]
Right, and it does not seem to be possible to trigger workflow manually to force release by running `gh workflow run Release` (as described [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)) for the first run:

```
$ gh workflow run Release 
could not create workflow dispatch event: HTTP 422: Workflow does not have 'workflow_dispatch' trigger (https://api.github.com/repos/terraform-aws-modules/terraform-aws-rds-aurora/actions/workflows/15013535/dispatches)
```

Good to know.

**Comment by antonbabenko** [comment]
Should we add `workflow_dispatch` as triggers?

**Comment by antonbabenko** [comment]
I added it in #251

**Pull request merged**
