### PR TITLE
Fixing alignment

### PR DESCRIPTION
**Pull request by max-rocket-internet**
Don't know why `terraform fmt` doesn't fix these.

### CODE REVIEW

**Comment by antonbabenko** [comment]
`main.tf` seemed to be formatted well before, so you should not have updated it manually.

README.md is not processed by `fmt`, so it is good that you fixed it manually.

**Comment by max-rocket-internet** [comment]
But `fmt` doesn't revert the changes to main.tf after fixing the alignment. So it's not like this change is going against `fmt`?

How do you think this:

```
resource "aws_iam_role_policy_attachment" "rds_enhanced_monitoring" {
  count      = "${var.monitoring_interval > 0 ? 1 : 0}"
  role       = "${aws_iam_role.rds_enhanced_monitoring.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}
```

Is better than this?

```
resource "aws_iam_role_policy_attachment" "rds_enhanced_monitoring" {
  count = "${var.monitoring_interval > 0 ? 1 : 0}"
  role       = "${aws_iam_role.rds_enhanced_monitoring.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}
```

**Comment by max-rocket-internet** [comment]
Ahh, I get it. `fmt` isn't fixing the alignment because of the extra blank line after `count`. Remove the blank lines, run `fmt` and then it fixes all the alignment exactly like in this PR.

**Comment by max-rocket-internet** [comment]
Can we merge this @antonbabenko ?

**Comment by max-rocket-internet** [comment]
OK no worries, as you wish.

**Pull request closed without merging**
