### PR TITLE
chore: Correct typo/misspelling

### PR DESCRIPTION
**Pull request by jensenbox**
## Description

Typo

## Motivation and Context

Just perusing and noticed it.

## Breaking Changes

None

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thanks for the PR @jensenbox - we'll need to do two things:
1. Update the PR title to something like `chore: Correct typo mis-spelling` 
2. Update documentation with `pre-commit run -a`

**Comment by jensenbox** [comment]
Done.

Do you think it would be worthwhile adding the Conventional Commits requirement and the `pre-commit` run to the PR template?

**Comment by bryantbiggs** [comment]
We have a GitHub action that checks, its just not firing since you are a first time contributor

**Review by bryantbiggs — APPROVED** [review]
@antonbabenko 👍🏽

**Comment by antonbabenko** [comment]
This PR is included in version 7.0.0 :tada:

**Pull request merged**
