### PR TITLE
feat: Do not create `snapshot_identifier` when `skip_final_snapshot = true`

### PR DESCRIPTION
**Pull request by air3ijai**
## Description
Do not create `random_id` for `snapshot_identifier` when `skip_final_snapshot = true` because it is not required.

## Motivation and Context
When we set `skip_final_snapshot = true` it is not required to generate `snapshot_identifier`. In current implementation it is still generated.

Screen Shot 2022-10-18 at 20 23 57

## Breaking Changes
No breaking changes

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
we'll need to change `skip_final_snapshot` default value to `false` which matches the API but is more explicit here for the conditional checking requirements. Don't forget to run `pre-commit run -a` after changing to update the docs/etc.

**Comment by air3ijai** [comment]
I added a default value and also run a `pre-commit run -a` and got a lot of errors, but at least docs passed
```
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
```
Screen Shot 2022-10-18 at 23 48 42

**Comment by air3ijai** [comment]
Documentation updated in PR
Screen Shot 2022-10-19 at 17 31 44

**Comment by antonbabenko** [comment]
This PR is included in version 7.6.0 :tada:

**Pull request merged**
