### PR TITLE
feat: Added conditional creation of RDS Aurora cluster

### LINKED ISSUE #157: Issue when using the module to create a secondary cluster as part of a Global Aurora database
Hi. There is an issue when using the module to create a secondary cluster as part of a Global Aurora database.

For the first cluster to join the Global database, fine. But the secondary cluster cannot be created because credentials are passed while they should not and we cannot prevent that behavior right now.

Even if we don't pass a master password, the module creates one and passes it to the aws_rds_cluster resource.

(because of the line master_password      = var.password == "" ? random_password.master_password.result : var.password in main.tf)

And we get:

Error: error creating RDS cluster: InvalidParameterCombination: Cannot specify user name for cross region replication cluster
	status code: 400, request id: 5b1d2557-43a7-4c8f-bcd0-9c3c6ba90369

The module must find a way not to pass a username or password when creating a secondary cluster on a global database.

### PR DESCRIPTION
**Pull request by callaingit**
## Description
Add a new variable is_primary_cluster so we can fine-tune the behavior of local.master_password in a special situation that is a valid use-case for the module.

Note that I did not have to modify the code for username in a similar way because we can force it to "" and it will be passed as-is to aws_rds_cluster (leaving the parameter out is not good enough as the default value is "root" and again, we cannot pass a username or a password to aws_rds_cluster when creating a secondary cluster as part of an Aurora Global database.

## Motivation and Context
Without that, there is always a password passed to aws_rds_cluster and this is problematic when adding a secondary cluster to a Global Aurora database.

## Breaking Changes
None as the default value of the new variable makes the change seemless for existing users.

## How Has This Been Tested?
For various reasons (network security issues), I was able to test the same change outside of the repo where I had the module locally (cannot fetch it from the internet with my work setup) and I replicated the lines of code here, but I would not mark it as tested. However, the change is simple and obvious but still.

Fixes #157

### CODE REVIEW

**Comment by callaingit** [comment]
Guys, I'm new to contributing here so I am not sure what to do with the Semantic Pull Request check that did not pass.

**Review by dmattia — APPROVED** [review]

**Comment by dmattia** [comment]
Can you please rebase @callaingit

**Comment by callaingit** [comment]
HI @dmattia, I rebased and pushed the commits, hoping everything is ok.

**Review by haddadianhamed1 — APPROVED** [review]
LGTM

**Comment by haddadianhamed1** [comment]
hey guys great solution could we merge this pr?

**Comment by antonbabenko** [comment]
This PR introduces a break change, because it uses `count` and Terraform will try to change resources from single to a single element list. I will finish this PR now and bump a major release now.

**Comment by antonbabenko** [comment]
[v3.0.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v3.0.0) has been just released.

Thank you for this PR!

**Pull request closed without merging**
